# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

emLogit <- function(outcome, prediction, W, tol, maxIter, wisdom) {
    .Call('EBMAforecastbeta_emLogit', PACKAGE = 'EBMAforecastbeta', outcome, prediction, W, tol, maxIter, wisdom)
}

emNorm <- function(outcome, prediction, RSQ, W, tol, maxIter, wisdom, sigma2) {
    .Call('EBMAforecastbeta_emNorm', PACKAGE = 'EBMAforecastbeta', outcome, prediction, RSQ, W, tol, maxIter, wisdom, sigma2)
}

